spring:
  application:
    name: ProfileService
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/HackatonSpring2024
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
server:
  port: 8082
token:
  secret:
    key: xE1OI98WRCvFy3mxH2KFQ5VRWmZvjFzlAE+yFadQJrQ=